//! ROCm/HIP backend — maps YOYO TIR operations to HIP C++ source.
//!
//! Produces a `.hip` C++ source file that can be compiled by `hipcc`.
//! Each TIR instruction is emitted as a C++ comment describing the operation.

use crate::tir::{instr_branch_kind, BranchKind, TirInst, TirOp};
use crate::types::IsaResult;

/// Emit HIP C++ text from TIR instructions.
pub fn emit_rocm(tir: &[TirInst]) -> IsaResult<String> {
    let mut hip = String::new();

    // HIP header
    hip.push_str("// HIP kernel generated by YOYO verifier\n");
    hip.push_str("#include <hip/hip_runtime.h>\n\n");
    hip.push_str("extern \"C\" __global__ void kernel_function(unsigned long long* state) {\n");

    // Collect data bytes for constant declaration
    let mut data_bytes: Vec<u8> = Vec::new();
    for inst in tir {
        match inst.op {
            TirOp::Data | TirOp::Str | TirOp::Raw => {
                for v in &inst.args {
                    data_bytes.push(*v as u8);
                }
            }
            _ => {}
        }
    }

    if !data_bytes.is_empty() {
        hip.push_str("    // Data section\n");
        hip.push_str("    __constant__ unsigned char data_bytes[] = { ");
        for (i, b) in data_bytes.iter().enumerate() {
            if i > 0 {
                hip.push_str(", ");
            }
            hip.push_str(&format!("0x{:02x}", b));
        }
        hip.push_str(" };\n\n");
    }

    // Build label map from handler definitions
    let mut label_map: std::collections::HashMap<u16, String> = std::collections::HashMap::new();
    for inst in tir {
        if let TirOp::Handler = inst.op {
            let hh = inst.args.first().copied().unwrap_or(0) as u16;
            label_map.insert(hh, format!("H_{:02X}", hh));
        }
    }

    // Emit instructions for each handler
    let mut in_handler = false;

    for inst in tir {
        match instr_branch_kind(inst.op) {
            BranchKind::LabelDef => {
                if in_handler {
                    hip.push_str("    // ret\n");
                }
                let hh = inst.args.first().copied().unwrap_or(0) as u16;
                let label = label_map.get(&hh).cloned().unwrap_or_else(|| format!("H_{:02X}", hh));
                hip.push_str(&format!("\n    // -- {} --\n", label));
                in_handler = true;
            }
            BranchKind::Ret => {
                // ret emitted when we close the handler (next HANDLER or end)
            }
            BranchKind::Call => {
                let hh = inst.args.first().copied().unwrap_or(0) as u16;
                let target = label_map.get(&hh).cloned().unwrap_or_else(|| format!("H_{:02X}", hh));
                hip.push_str(&format!("    // CALL {}\n", target));
            }
            BranchKind::Jmp => {
                let hh = inst.args.first().copied().unwrap_or(0) as u16;
                let target = label_map.get(&hh).cloned().unwrap_or_else(|| format!("H_{:02X}", hh));
                hip.push_str(&format!("    // JMP {}\n", target));
            }
            BranchKind::Jcc { index: _ } => {
                let hh = inst.args.first().copied().unwrap_or(0) as u16;
                let target = label_map.get(&hh).cloned().unwrap_or_else(|| format!("H_{:02X}", hh));
                hip.push_str(&format!("    // JCC {}\n", target));
            }
            BranchKind::None => {
                emit_hip_inst(&mut hip, inst)?;
            }
        }
    }

    // Close last handler
    if in_handler {
        hip.push_str("    // ret\n");
    }

    hip.push_str("}\n");
    Ok(hip)
}

/// Emit a single non-branch TIR instruction as a HIP C++ comment.
fn emit_hip_inst(hip: &mut String, inst: &TirInst) -> IsaResult<()> {
    let a = |i: usize| inst.args.get(i).copied().unwrap_or(0);

    match inst.op {
        TirOp::Nop => {
            hip.push_str("    // NOP\n");
        }
        TirOp::Data | TirOp::Str | TirOp::Raw => {
            // Data is emitted in the constant section; nothing to do in code
        }
        TirOp::Alloc => {
            let slot = a(0) as u16;
            let size = a(1);
            hip.push_str(&format!("    // ALLOC slot={}, size={}\n", slot, size));
        }
        TirOp::Set => {
            let slot = a(0) as u16;
            let imm = a(1);
            hip.push_str(&format!("    // SET slot={}, imm=0x{:x}\n", slot, imm));
        }
        TirOp::Get | TirOp::Movrr => {
            let dst = a(0) as u16;
            let src = a(1) as u16;
            hip.push_str(&format!("    // GET state[{}] = state[{}]\n", dst, src));
        }
        TirOp::Add => {
            let slot = a(0) as u16;
            let imm = a(1);
            hip.push_str(&format!("    // ADD state[{}] += {}\n", slot, imm));
        }
        TirOp::Sub => {
            let slot = a(0) as u16;
            let imm = a(1);
            hip.push_str(&format!("    // SUB state[{}] -= {}\n", slot, imm));
        }
        TirOp::Inc => {
            let slot = a(0) as u16;
            hip.push_str(&format!("    // INC state[{}]++\n", slot));
        }
        TirOp::Dec => {
            let slot = a(0) as u16;
            hip.push_str(&format!("    // DEC state[{}]--\n", slot));
        }
        TirOp::Addv => {
            let dst = a(0) as u16;
            let src = a(1) as u16;
            hip.push_str(&format!("    // ADDV state[{}] += state[{}]\n", dst, src));
        }
        TirOp::Orv => {
            let dst = a(0) as u16;
            let src = a(1) as u16;
            hip.push_str(&format!("    // ORV state[{}] |= state[{}]\n", dst, src));
        }
        TirOp::Subv => {
            let dst = a(0) as u16;
            let src = a(1) as u16;
            hip.push_str(&format!("    // SUBV state[{}] -= state[{}]\n", dst, src));
        }
        TirOp::Imul => {
            let dst = a(0) as u16;
            let src = a(1) as u16;
            hip.push_str(&format!("    // IMUL state[{}] *= state[{}]\n", dst, src));
        }
        TirOp::Cmp => {
            let a_slot = a(0) as u16;
            let b_slot = a(1) as u16;
            hip.push_str(&format!("    // CMP state[{}] == state[{}]\n", a_slot, b_slot));
        }
        TirOp::Ldb => {
            let dd = a(0) as u16;
            let ss = a(1) as u16;
            let oo = a(2) as u16;
            hip.push_str(&format!("    // LDB state[{}] = *(u8*)(state[{}] + {})\n", dd, ss, oo));
        }
        TirOp::LoadFile => {
            let slot = a(0) as u16;
            let str_idx = a(1);
            hip.push_str(&format!("    // LOAD_FILE state[{}] = fopen(str{})\n", slot, str_idx));
        }
        TirOp::WriteFile => {
            let slot = a(0) as u16;
            let str_idx = a(1);
            hip.push_str(&format!("    // WRITE_FILE state[{}] -> str{}\n", slot, str_idx));
        }
        TirOp::MemcpyData => {
            let dst = a(0) as u16;
            let src = a(1) as u16;
            let n = a(2) as u16;
            hip.push_str(&format!("    // MEMCPY_DATA memcpy(data+{}, state[{}], {})\n", dst, src, n));
        }
        TirOp::MemcpyState => {
            let dst = a(0) as u16;
            let src = a(1) as u16;
            let n = a(2) as u16;
            hip.push_str(&format!("    // MEMCPY_STATE memcpy(state+{}, state+{}, {})\n", dst, src, n));
        }
        TirOp::Raw | TirOp::Data | TirOp::Str => {
            // handled above
        }
        TirOp::Handler => {
            // handled in branch dispatch
        }
        _ => {
            let code = a(0) as u8;
            hip.push_str(&format!("    // EXIT code={}\n", code));
        }
    }
    Ok(())
}