//! Self-host framework — x64 dispatch for `--selfhost` PE.
//!
//! Architecture:
//!   .text: [selfhost_startup] [handler_bytes] [HOT_table]
//!
//! selfhost_startup is x64 machine code that:
//!   1. Reads .tyb from argv[1]
//!   2. For each 8B record: HOT lookup → copy handler bytes to output buffer
//!   3. Builds PE header around output buffer
//!   4. Writes output .exe
//!
//! "Copy, not call" — the handler bytes are pre-computed by yoyo.exe at link time.
//! M1.exe doesn't need emit functions, just the pre-computed results.

use crate::types::IsaResult;

/// HOT entry: [opcode:1][argc:1][a0:2][a1:2][a2:2][offset:4][len:2] = 14 bytes
/// Keyed by (opcode, args) so the same opcode+args always maps to the same bytes.
pub const HOT_ENTRY_SIZE: usize = 14;

/// Build the HOT table.
/// Each entry maps (opcode, argc, a0, a1, a2) → (code_offset, byte_length).
/// Keyed by the full 8B record so dispatch is a simple binary search.
pub fn build_hot(handler_offsets: &[(u16, u32, u32)]) -> Vec<u8> {
    // V1: build a simple linear lookup table.
    // Each entry: [hh:2][offset:4][len:2] = 8 bytes
    // Terminated by 0xFFFF.
    let mut hot = Vec::new();
    for (hh, off, len) in handler_offsets {
        hot.extend_from_slice(&hh.to_le_bytes());
        hot.extend_from_slice(&off.to_le_bytes());
        hot.extend_from_slice(&(*len as u16).to_le_bytes());
    }
    hot.extend_from_slice(&0xFFFFu16.to_le_bytes());
    hot
}

/// Generate the selfhost startup x64 code.
///
/// This is the entry point of the --selfhost PE.
/// It reads .tyb, looks up handlers in HOT, copies bytes, writes output PE.
///
/// hot_va: absolute VA of the HOT table (image_base + hot_rva)
/// code_va: absolute VA of the first handler byte
/// startup_va: absolute VA of the startup code itself
pub fn gen_selfhost_startup(hot_va: u64, code_va: u64, startup_va: u64) -> Vec<u8> {
    // The startup code is pure x64 machine code that:
    //
    // 1. Open .tyb file (argv[1]) via CreateFileA
    // 2. Read file into heap via ReadFile
    // 3. Iterate 8B records
    // 4. For each record: linear search HOT → copy handler bytes to output
    // 5. Build PE header around output
    // 6. Write output file via CreateFileA + WriteFile
    // 7. Exit(0)
    //
    // This is ~500 bytes of x64. For V1, we emit a simpler version:
    // The startup code is pre-generated by yoyo.exe at link time.
    // It has the HOT address and code address baked in as immediates.
    //
    // For now, V1 is a stub that exits with code 42 (to indicate selfhost mode).
    // Full implementation will be added incrementally.

    let mut code: Vec<u8> = Vec::new();

    // V1: simple exit(42) stub
    // mov eax, 42
    code.extend_from_slice(&[0xB8, 0x2A, 0x00, 0x00, 0x00]);
    // ret
    code.push(0xC3);

    code
}